service: recognition-slackbot

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    ACCESS_TOKEN: ${file(local.yml):slack.accessToken}
  region: ap-northeast-1

functions:
  event:
    handler: handler.event
    events: 
      - http:
          path: event
          method: post
 